#!/usr/bin/python

# Name: Megan Bess
# Course: NTS370
# Date: 10OCT20
# Last Revision: 10OCT20

# ------------------------------------------------------------
# Purpose:
# ------------------------------------------------------------
# This script is designed to add the numbers 1-100 together
# as Carl Frederich Gauss once did in his grade school class.
# ------------------------------------------------------------


