#!/usr/bin/python

# Name: Megan Bess
# Course: NTS370
# Date: 10OCT20
# Last Revision: 10OCT20

# --------------------------------------------------------------------
# Purpose:
# --------------------------------------------------------------------
# This script defines a series of functions with the lyrics of a song
# and prints them to the screen, using them to save space when things repeat.
# --------------------------------------------------------------------

def verse1():
	print('''
		Have faith in me,
		Cause there are things that I've seen I don't believe.
		So cling to what you know, and never let go,
		You should know, things aren't always what they seem.
	     ''')

def verse2():
	print('''
		I'm going crazy,
		Cause there are things in the streets I don't believe.
		So we'll pretend it's alright (pretend it's alright),
		and stay for the night.
		Oh what a world. I'll keep you safe here with me (with me).
	     ''')

def bridge():
	print('''
		They've got me on the outside looking in.
		But I can't see at all,
		With the weight of the world on my shoulders,
		They just wanna see me fall.
	     ''')

def refrain():
	print('''
		I said I'd never let you go, and I never did.
		I said I'd never let you fall and I always meant it.
		If you didn't have a chance, then I never did.
		You'll always find me right there, again.
	     ''')

verse1()
refrain()
verse2()
refrain()
refrain()
bridge()
bridge()
refrain()
refrain()

for i in range(4):
	print("                I said I'd never let you go, and I never did.")

